### ISSUE TITLE
Do we create a ducument using the new metanorma with lutaml for UML diagrams

### ISSUE THREAD

**Issue by rggibb** [opengeospatial/dggs-2-equi-volume#1]
lutaml is a metanorma plug-in supporting UML data models in the document, represented in diagrams with their attributes described in text. Lutaml is documented [here](https://www.metanorma.org/author/topics/automation/datamodel/) as part of the metanorma documentation.

In OGC AS 21 DGGS v2.0 / ISO 19170-1, which was developed before lutam, l was available UML diagrams were exported from EA as images, and I wrote a python script used with shapechange's feature catalogue exported to create entity/attribute definition tables.

With lutaml the diagrams are extracted from EA as SVG with annotation as text, which makes the UML diagram text searchable in the final document, and the attrbutes are more completely extracted than in feature catalogue approach.

**Comment by geofizzydrink** [comment]
yep

**Comment by rggibb** [comment]
Agreed at 2021-06-15 TC DGGS SWG, NOTUC
